site_name: SAGIRI BOT Docs
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 前言: index.md
  - 项目部署:
    - Windows: deployment/windows.md
    - Linux: deployment/linux.md
    - Android: deployment/android.md
  - 配置文件: configuration.md
  - 功能:
    - 必要插件（建议不删除）: functions/required_module.md
    - 内置插件（可删除）: functions/handlers.md
  - 功能拓展: function_extension.md
  - 二次开发:
      - 开始开发: development/start.md
      - 内置控制器: development/control.md
  - 管理: manage.md
  - 更新日志: update.md
  - FAQ: FAQ.md
  - 关于: about.md
repo_url: https://github.com/SAGIRI-kawaii/sagiri-bot
repo_name: SAGIRI-kawaii/sagiri-bot
dev_addr: '127.0.0.1:6789'